name: ship-list

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  verify:
    uses: RimWorks/mod-ci/.github/workflows/ship-list.yml@3fc79fa70496f2d785d8b0ba485ba6f213f9c264 # v1.8.0
    with:
      ref: 3fc79fa70496f2d785d8b0ba485ba6f213f9c264 # v1.8.0
